/* =========================================================
   ONE-TIME SITE CONFIG
   You normally do NOT edit this file when adding videos.
   ========================================================= */

window.SITE_CONFIG = {
  handle: "@itneverbegunn",
  tiktokURL: "https://www.tiktok.com/@itneverbegunn",

  // IntenseDebate site account ID
  intenseDebateAccountId: "5d7f917fb33672c48d3d9f0a463d3123",

  goatCounterURL: "https://sainthamudidisciple.goatcounter.com/count",
  reactionNamespace: "itneverbegunn"
};
