/* =========================================================
   ONE-TIME SITE CONFIG
   You normally do NOT edit this file when adding videos.
   ========================================================= */

window.SITE_CONFIG = {
  handle: "@itneverbegunn",
  tiktokURL: "https://www.tiktok.com/@itneverbegunn",

  // Paste the value IntenseDebate gives your registered site here once.
  // Leave blank to hide the comments section completely.
  intenseDebateAccountId: "",

  goatCounterURL: "https://sainthamudidisciple.goatcounter.com/count",
  reactionNamespace: "itneverbegunn"
};
